#!/usr/bin/env bash
# Script that install nginx web server

sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
