#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

# Starts up nginx
sudo apt-get update 
sudo apt-get install -y nginx 

#Add header of X-Served-by
sudo sed -i '11a \ \tadd_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
