#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it

FILE=$(date +%d-%m-%Y).tar.gz
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -cfvz "$FILE" backup.sql
