#!/usr/bin/env bash
# Bash script that  generates a MySQLdump and creates a compressed archive out of it
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -cfvz "$(date +%d-%m-%Y).tar.gz" backup.sql
