#!/usr/bin/env bash
# Pings an ip 5 times
# If no argument displays, Usage: 5-is_the_host_on_the_network {IP_ADDRESS}


if [ $# -ne 0 ]
then
    ping -c 5 "$1"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
