#!/bin/bash
# Script that displays the content of the file /etc/passwd, using the while loop + IFS

file="/etc/passwd"

while IFS=: read -r USERNAME PASSWORD ID GROUP_ID COMMENT HOME_DIRECTORY COMMANDSHELL
do
  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMANDSHELL. $ID's place is protected by the passcode $PASSWORD, more info about the user here: $COMMENT"
done < $file

