#!/usr/bin/env bash
# Script that displays "Holberton School" 10 times and prints Hi on the 9th iteration

i=1

while [ $i -le  10 ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
   ((i++))
done
