#!/usr/bin/env bash
# Script that displays Holberton School 10 except for the 4th and 8th iteration

i=1

while ((i <=  10))
do
    if ((i == 4))
    then
        echo "bad luck"
    elif ((i == 8))
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i++))
done
