#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes

h=0 #hours

while ((h <= 12))
do
    echo "Hour: $h"
    m=1 #minutes
    while ((m <= 59))
    do
        echo "$m"
        ((m++))
    done
    ((h++))
done
