#!/usr/bin/env bash
# Script thatconfigures a Ubuntu server with
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8


cp /etc/hosts ~/temp_hosts
sed -i s/127.0.0.1/127.0.0.2/ ~/temp_hosts
echo "8.8.8.8 facebook.com" >> ~/temp_hosts
cp -f ~/temp_hosts /etc/hosts
